### ISSUE TITLE
Problem consultation

### ISSUE THREAD

**Issue by Mrhard1999** [zkawfanx/GTAV-NightRain#1]
Do you use the big version of data set or the released small version of data set to train the code of the article clock? Looking forward to your answer?

**Comment by zkawfanx** [comment]
Do you mean the data used for the experiments of the arxiv paper? The experiments were conducted using the initial big version of the dataset and the small set is meant for the convenience of you on downloading and quick checking the data.

**Comment by Mrhard1999** [comment]
> Do you mean the data used for the experiments of the arxiv paper? The experiments were conducted using the initial big version of the dataset and the small set is meant for the convenience of you on downloading and quick checking the data.
Thank you for your reply. I saw that one rainless image corresponded to 10 rainless images in your data set. Do you need to make 10 copies of rainless images to form a pairing relationship with rainless images during training?

**Comment by Mrhard1999** [comment]
Thank you for your reply. I saw that one rainless image corresponded to 10 rainy images in your data set. Do you need to make 10 copies of rainless images to form a pairing relationship with rainy images during training?

> Do you mean the data used for the experiments of the arxiv paper? The experiments were conducted using the initial big version of the dataset and the small set is meant for the convenience of you on downloading and quick checking the data.

Thank you for your reply. I saw that one rainless image corresponded to 10 rainy images in your data set. Do you need to make 10 copies of rainless images to form a pairing relationship with rainy images during training?

**Comment by Mrhard1999** [comment]
Thank you for your reply. I saw that one rainless image corresponded to 10 rainy images in your data set. Do you need to make 10 copies of rainless images to form a pairing relationship with rainy images during training?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zkawfanx/GTAV-NightRain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月4日(星期四) 晚上9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zkawfanx/GTAV-NightRain] Problem consultation (Issue #1)





 
Do you mean the data used for the experiments of the arxiv paper? The experiments were conducted using the initial big version of the dataset and the small set is meant for the convenience of you on downloading and quick checking the data.

**Comment by zkawfanx** [comment]
You can either copy the image file or make paired file paths to construct the pair relationship. Feel free to try on your own.
